import "@styles/globals.css";
import type { AppProps } from "next/app";
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import Head from "next/head";

const theme = extendTheme({
  styles: {
    global: {
      "*": {
        fontFamily: "Plus Jakarta Sans",
      },
      a: {
        _hover: {
          textDecoration: "none !important",
        },
      },
    },
  },
});

function MyApp({ Component, pageProps, router }: AppProps) {
  return (
    <ChakraProvider theme={theme}>
      <Head>
        <title>TrustSight: Enabling Trust on Tron</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="fixed-background" />
      <Component {...pageProps} key={router.route} />
    </ChakraProvider>
  );
}

export default MyApp;
