import "@styles/globals.css";
import type { AppProps } from "next/app";
import { useEffect, useState } from "react";
import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import Head from "next/head";
import { selectAnatomy } from "@chakra-ui/anatomy";
import { createMultiStyleConfigHelpers } from "@chakra-ui/react";
import Navbar from "@components/Navbar";
import { TronProvider } from "@components/TronProvider";

const { definePartsStyle, defineMultiStyleConfig } =
  createMultiStyleConfigHelpers(selectAnatomy.keys);

const custom = definePartsStyle({
  field: {
    background: "blue.100",
    borderRadius: "20px !important",
    fontWeight: "700 !important",
  },
});

const selectTheme = defineMultiStyleConfig({
  variants: { custom },
});

const theme = extendTheme({
  styles: {
    global: {
      "*": {
        fontFamily: "Plus Jakarta Sans",
        color: "black",
      },
      a: {
        _hover: {
          textDecoration: "none !important",
        },
      },
    },
    components: {
      Select: selectTheme,
    },
  },
});

function MyApp({ Component, pageProps, router }: AppProps) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);
  if (!mounted) return null;

  return (
    <TronProvider>
      <ChakraProvider theme={theme}>
        <Head>
          <title>TrustSight: Enabling Trust on Tron</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <div className="fixed-background" />
        <Component {...pageProps} key={router.route} />
      </ChakraProvider>
    </TronProvider>
  );
}

export default MyApp;
